### ISSUE TITLE
RESTRequest1.Execute returns URL error

### ISSUE THREAD

**Issue by FactoryXCode** [SteveNew/FoilCast#1]
Hi,

RESTRequest1.Execute returns an URL error, because somehow a backslash is added before https//..

The URL I tried was: "https://www.youtube.com/watch?v=ooYMvzxPXSc"

The source URL however is translated as:
`TESTSTRING := RESTRequest1.GetFullRequestURL(true);`
The result is: '/http://192.168.1.41:8008/apps/YouTube?v=ooYMvzxPXSc' < Notice the backslash at the beginning of the URL.

I tested the code on Delphi 10.3.1 and 10.3.3, both with the same result.

**Comment by SteveNew** [comment]
Yes it seems that time has taken its toll on this example code.

The extra '/' seem to be cause by not setting the baseURL on the TRESTClient which then leads the revised 10.3.x GetFullURL code to prefix it.

But even after that it seems that the requirement for https and possibly also an api key - means that the FoilCast YouTube example is broken - it will not work with XE7 either due to ChromeCast firmware changes it seems.

So it might be a good idea to update the post from 2014 - I will put it on my list ....

By removing the '/' you might get a bit further but will probably get a 404. The idea would be to intercept what it sent like the apikey and so on - but it seems more complex than that. So best way might be to walk past googles developer chromecast site.

I will close this since it is basically about the changes in REST code from EMBT side, and setting baseURL seems to solve that.

**Comment by SteveNew** [comment]
One final note: It seems they also moved from DIAL to mDNS protocol...I do not use my ChromeCast that often currently.

**Comment by FactoryXCode** [comment]
Thanks! 
I found a C++ translation of the ChromeCast Api, in the VLCPlayer's sources, which is more suitable to translate to Delphi for the Windows platform. I'm currently working on that one.

**Comment by FactoryXCode** [comment]
By the way: To discover the ChromeCast devices, the easiest way is to use the Indy components: IdIPMCastClient (2 times, one for the old DIAL protocol and one for the new mDSN protocol). 

For both use the callback OnIPMCastRead to read the data.
For example:

`procedure TForm1.IdIPMCastClient1IPMCastRead(Sender: TObject;
  const AData: TIdBytes; ABinding: TIdSocketHandle);

var
 Str: String;
 TextEncoding: IIdTextEncoding;

begin
  Str := BytesToString(AData,
                       0,
                       Length(AData),
                       TextEncoding);

  { do something with textencoding, or not }
  { should be decoded the proper way, to get rid of the #0 characters. } 
  
  memo1.Lines.Append(Trim(Str));
  
  memo1.Lines.Append('Socket info: ------------------------------- ');
  memo1.Lines.Append('PeerIP: ' + ABinding.PeerIP);
  memo1.Lines.Append('PeerPort: ' + IntToStr(ABinding.PeerPort));
  memo1.Lines.Append('-------------------------------------------- ');
  Application.ProcessMessages;
end;`

Both components should be issued with:
IdIPMCastClient1  ( mSDN protocol )
  Bindings = 0.0.0.0:5353
  DefaultPort = 5353
  MultiCastGroup = 224.0. 0.251
  ReuseSocket = true
  ThreadedEvent = true

IdIPMCastClient2  ( DIAL protocol )
  Bindings = 0.0.0.0:1900
  DefaultPort = 1900
  MultiCastGroup = 239.255.255.250
  ReuseSocket = true
  ThreadedEvent = true

Note: You will get messages from GoogleDrive, MS MediaServer and Google Sync as well..

Greetings, Tony.
